---
parameters:
- name: cloud
  brief: Cloud
  kind: user
  parameters:
  - name: kind
    value: aws
  - name: region
    fromEnv: AWS_REGION
- name: dns
  brief: DNS
  kind: user
  parameters:
  - name: name
    brief: DNS name
    fromEnv: PLATFORM_NAME
  - name: baseDomain
    brief: DNS base domain
    fromEnv: BASE_DOMAIN
    default: superhub.io
  - name: domain
    value: ${dns.name}.${dns.baseDomain}
- name: component.storage-class.name
  value: default
- name: terraform.bucket
  brief: Terraform state location
  parameters:
  - name: name
    fromEnv: STATE_BUCKET
  - name: region
    fromEnv: STATE_REGION
- name: component.ingress
  parameters:
  - name: dashboard
    value: 'true'
  - name: ssoUrlPrefix
    value: apps
  - name: urlPrefix
    value: app
