---
parameters:
- name: cloud
  brief: Cloud
  kind: user
  parameters:
  - name: kind
    value: aws
  - name: region
    fromEnv: AWS_REGION
- name: dns
  brief: DNS
  kind: user
  parameters:
  - name: name
    brief: DNS name
    fromEnv: PLATFORM_NAME
  - name: baseDomain
    brief: DNS base domain
    fromEnv: BASE_DOMAIN
    default: superhub.io
  - name: domain
    value: ${dns.name}.${dns.baseDomain}
- name: component.storage-class.name
  value: default
- name: terraform.bucket
  brief: Terraform state location
  parameters:
  - name: name
    fromEnv: STATE_BUCKET
  - name: region
    fromEnv: STATE_REGION
- name: component.ingress
  parameters:
  - name: dashboard
    value: 'true'
  - name: ssoUrlPrefix
    value: apps
  - name: urlPrefix
    value: app
- name: component.istio
  parameters:
  - name: version.release
    value: 1.3.8
  - name: prometheus.enabled
    # this parameter is deprecated
    # it will be removed in the future
    value: "true"
- name: component.kubeflow
  parameters:
  - name: name
    value: kubeflow
  - name: namespace
    value: ${component.kubeflow.name}
  - name: passwd
    parameters:
    - name: 0.user
      value: admin@agilestacks.com
      env: HUB_DEX_USER
    - name: 0.password
      value: 12341234
      env: PLAIN_PASS

- name: component.prometheus
  parameters: 
  - name: prometheus.volumeSize
    value: 12Gi
  - name: prometheus.retention
    value: 4h

- name: component.dex
  parameters: 
  - name: issuer
    value: https://auth.${dns.domain}
  - name: namespace
    value: kube-system

